"""add application_notes model

Revision ID: 18144e17ddfb
Revises: edcab7fe9440
Create Date: 2026-06-28 19:35:11.874767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18144e17ddfb'
down_revision: Union[str, Sequence[str], None] = 'edcab7fe9440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.Enum('apply', 'interview', 'question', 'feedback', 'general', name='note_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_notes_application_id'), 'application_notes', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_notes_note_type'), 'application_notes', ['note_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_notes_note_type'), table_name='application_notes')
    op.drop_index(op.f('ix_application_notes_application_id'), table_name='application_notes')
    op.drop_table('application_notes')
    # ### end Alembic commands ###
