"""add application_notes model

No-op revision: duplicate autogenerate run after 18144e17ddfb, which already
created application_notes. Kept for Alembic history on deployed databases.

Revision ID: 295c1c5ae74f
Revises: 18144e17ddfb
Create Date: 2026-06-28 19:39:59.188588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295c1c5ae74f'
down_revision: Union[str, Sequence[str], None] = '18144e17ddfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
