"""add job_applications core model

Revision ID: edcab7fe9440
Revises: 372e8b60d1c5
Create Date: 2026-06-28 19:22:07.537701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcab7fe9440'
down_revision: Union[str, Sequence[str], None] = '372e8b60d1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('jd_url', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Enum('full_time', 'internship', 'freelance', name='job_type_enum'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('expected_salary', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('applied', 'screening', 'interview', 'offer', 'rejected', 'on_hold', name='application_status_enum'), server_default='applied', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_applied_at'), 'job_applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_job_applications_company_name'), 'job_applications', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_applications_status'), 'job_applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_status'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_company_name'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_applied_at'), table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
